name: Build and release

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pages: write
      id-token: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup beam
        uses: erlef/setup-beam@v1.16.0
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"
          elixir-version: "1.17"
      - name: Install dependencies
        run: gleam deps download
      - name: Build app
        run: gleam run -m lustre/dev build app --minify
      - name: Copy output to dist
        run: |
          mkdir -p dist
          cp index.html dist/index.html
          cp -r priv dist/priv
      - name: Update path in index.html to use minified app
        run: sed -i 's|priv/static/timetracker_gleam.mjs|priv/static/timetracker_gleam.min.mjs|' dist/index.html
      - name: run tailwind
        run: npm run tw_build
      - name: push to site branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "{msg}"
